services:
  - type: web
    name: houseflow-tuya-api
    runtime: docker
    plan: free
    dockerfilePath: ./Houseflow.Api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/status
    envVars:
      - key: TUYA_BASE_URL
        value: https://openapi.tuyaeu.com
      - key: FRONTEND_ORIGINS
        value: https://alinmangeac.github.io
